### ISSUE TITLE
Network and Qemu related

### ISSUE THREAD

**Issue by RobertHa** [malsami/distributor_service#3]
#### In [distributor.py](../blob/master/distributor.py):
- [x] \_create\_bridge() function should create a bridge and return the object 
- [x] \_kill\_log\_killer() as function for a thread to scan the kill\_log for entries and kill the appearing qemus
#### In [machine.py](../blob/master/machine.py):
- [x] \_create\_tap\_device() to create a tap device on the provided bridge and return it created object
- [x] \_spawn\_host(): see comments for necessary functionality

**Comment by vbahl2** [comment]
_kill_log_killer uses infinite loop in python instead of bash to continually read file. 

_spawn_host() returns the pid and stores a dictionary with which maps ip -> pid. Pids are for easy killing of processes
