### ISSUE TITLE
system failure

### ISSUE THREAD

**Issue by RobertHa** [malsami/distributor_service#9]
For unknown reasons the whole setup stops after a certain time when executed in a vagrant machine.

This can happen after a few hours or even days.

Memory usage is not at fault.

**Comment by RobertHa** [comment]
No error messages are prompted or logged. 
All logs stop at the same time.

**Comment by RobertHa** [comment]
apparently this only happens inside a Vagrant machine

**Comment by BugUser0815** [comment]
Does this have any disadvantages?

**Comment by BugUser0815** [comment]
Do we already know why this happened?
Does this still happen?

**Comment by privatereese** [comment]
Is this still relevant, do we have a solution for it? @RobertHa

**Comment by RobertHa** [comment]
I have not seen it happen since, but we do not use vagrant for data generation. Vagrant is only used as development and testing environment for short tests. Thus even if the error still occurs, I would not deem it important.
